//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvisorConfig) DeepCopyInto(out *AdvisorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvisorConfig.
func (in *AdvisorConfig) DeepCopy() *AdvisorConfig {
	if in == nil {
		return nil
	}
	out := new(AdvisorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUSetConfig) DeepCopyInto(out *CPUSetConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUSetConfig.
func (in *CPUSetConfig) DeepCopy() *CPUSetConfig {
	if in == nil {
		return nil
	}
	out := new(CPUSetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUSetPool) DeepCopyInto(out *CPUSetPool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUSetPool.
func (in *CPUSetPool) DeepCopy() *CPUSetPool {
	if in == nil {
		return nil
	}
	out := new(CPUSetPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionConfig) DeepCopyInto(out *EvictionConfig) {
	*out = *in
	if in.DisabledPlugins != nil {
		in, out := &in.DisabledPlugins, &out.DisabledPlugins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionConfig.
func (in *EvictionConfig) DeepCopy() *EvictionConfig {
	if in == nil {
		return nil
	}
	out := new(EvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePressure) DeepCopyInto(out *NodePressure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePressure.
func (in *NodePressure) DeepCopy() *NodePressure {
	if in == nil {
		return nil
	}
	out := new(NodePressure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceProfile) DeepCopyInto(out *NodeResourceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceProfile.
func (in *NodeResourceProfile) DeepCopy() *NodeResourceProfile {
	if in == nil {
		return nil
	}
	out := new(NodeResourceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeResourceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceProfileList) DeepCopyInto(out *NodeResourceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeResourceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceProfileList.
func (in *NodeResourceProfileList) DeepCopy() *NodeResourceProfileList {
	if in == nil {
		return nil
	}
	out := new(NodeResourceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeResourceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceProfileSpec) DeepCopyInto(out *NodeResourceProfileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceProfileSpec.
func (in *NodeResourceProfileSpec) DeepCopy() *NodeResourceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(NodeResourceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceProfileStatus) DeepCopyInto(out *NodeResourceProfileStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Allocatable != nil {
		in, out := &in.Allocatable, &out.Allocatable
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.QoSAllocations != nil {
		in, out := &in.QoSAllocations, &out.QoSAllocations
		*out = make(map[QoSLevel]QoSAllocation, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Reclaimable != nil {
		in, out := &in.Reclaimable, &out.Reclaimable
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	out.Pressure = in.Pressure
	if in.CPUSetPools != nil {
		in, out := &in.CPUSetPools, &out.CPUSetPools
		*out = make([]CPUSetPool, len(*in))
		copy(*out, *in)
	}
	if in.TopologyZones != nil {
		in, out := &in.TopologyZones, &out.TopologyZones
		*out = make([]TopologyZone, len(*in))
		copy(*out, *in)
	}
	in.LastReportTime.DeepCopyInto(&out.LastReportTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceProfileStatus.
func (in *NodeResourceProfileStatus) DeepCopy() *NodeResourceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(NodeResourceProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvercommitConfig) DeepCopyInto(out *OvercommitConfig) {
	*out = *in
	if in.MinReclaimCPU != nil {
		in, out := &in.MinReclaimCPU, &out.MinReclaimCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MinReclaimMemory != nil {
		in, out := &in.MinReclaimMemory, &out.MinReclaimMemory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvercommitConfig.
func (in *OvercommitConfig) DeepCopy() *OvercommitConfig {
	if in == nil {
		return nil
	}
	out := new(OvercommitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QoSAllocation) DeepCopyInto(out *QoSAllocation) {
	*out = *in
	if in.Requested != nil {
		in, out := &in.Requested, &out.Requested
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Actual != nil {
		in, out := &in.Actual, &out.Actual
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QoSAllocation.
func (in *QoSAllocation) DeepCopy() *QoSAllocation {
	if in == nil {
		return nil
	}
	out := new(QoSAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QoSPolicy) DeepCopyInto(out *QoSPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QoSPolicy.
func (in *QoSPolicy) DeepCopy() *QoSPolicy {
	if in == nil {
		return nil
	}
	out := new(QoSPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QoSPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QoSPolicyList) DeepCopyInto(out *QoSPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QoSPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QoSPolicyList.
func (in *QoSPolicyList) DeepCopy() *QoSPolicyList {
	if in == nil {
		return nil
	}
	out := new(QoSPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QoSPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QoSPolicySpec) DeepCopyInto(out *QoSPolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Overcommit.DeepCopyInto(&out.Overcommit)
	out.Advisor = in.Advisor
	in.Eviction.DeepCopyInto(&out.Eviction)
	out.CPUSet = in.CPUSet
	in.Webhook.DeepCopyInto(&out.Webhook)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QoSPolicySpec.
func (in *QoSPolicySpec) DeepCopy() *QoSPolicySpec {
	if in == nil {
		return nil
	}
	out := new(QoSPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QoSPolicyStatus) DeepCopyInto(out *QoSPolicyStatus) {
	*out = *in
	out.TotalReclaimableCPU = in.TotalReclaimableCPU.DeepCopy()
	out.TotalReclaimableMemory = in.TotalReclaimableMemory.DeepCopy()
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QoSPolicyStatus.
func (in *QoSPolicyStatus) DeepCopy() *QoSPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(QoSPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyZone) DeepCopyInto(out *TopologyZone) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyZone.
func (in *TopologyZone) DeepCopy() *TopologyZone {
	if in == nil {
		return nil
	}
	out := new(TopologyZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageStatistics) DeepCopyInto(out *UsageStatistics) {
	*out = *in
	out.P50 = in.P50.DeepCopy()
	out.P90 = in.P90.DeepCopy()
	out.P95 = in.P95.DeepCopy()
	out.P99 = in.P99.DeepCopy()
	out.Max = in.Max.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageStatistics.
func (in *UsageStatistics) DeepCopy() *UsageStatistics {
	if in == nil {
		return nil
	}
	out := new(UsageStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	if in.ExemptNamespaces != nil {
		in, out := &in.ExemptNamespaces, &out.ExemptNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProfile) DeepCopyInto(out *WorkloadProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProfile.
func (in *WorkloadProfile) DeepCopy() *WorkloadProfile {
	if in == nil {
		return nil
	}
	out := new(WorkloadProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProfileList) DeepCopyInto(out *WorkloadProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProfileList.
func (in *WorkloadProfileList) DeepCopy() *WorkloadProfileList {
	if in == nil {
		return nil
	}
	out := new(WorkloadProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProfileSpec) DeepCopyInto(out *WorkloadProfileSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProfileSpec.
func (in *WorkloadProfileSpec) DeepCopy() *WorkloadProfileSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProfileStatus) DeepCopyInto(out *WorkloadProfileStatus) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	in.Memory.DeepCopyInto(&out.Memory)
	if in.CurrentRequests != nil {
		in, out := &in.CurrentRequests, &out.CurrentRequests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Recommendation != nil {
		in, out := &in.Recommendation, &out.Recommendation
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProfileStatus.
func (in *WorkloadProfileStatus) DeepCopy() *WorkloadProfileStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadProfileStatus)
	in.DeepCopyInto(out)
	return out
}
